### ISSUE TITLE
It is a secure database ?

### ISSUE THREAD

**Issue by felixferr** [fosscom/objectdb#57]
Hi, i would like to know if it a secure db ?

**Comment by felixferr** [comment]
I saw there is no encryption support. My goal is to store content like book to be read by user. So it is a good db for my use case ? Thx

**Comment by marioreggiori** [comment]
Hi @felixferr i was planning on adding encrypted storage files. But since there isn't an official encryption lib for Dart this feature is still pending.

If you Plan to store whole books into the database, I think objectdb isn't the right one for your usecase. But you could store those books directly onto the filesystem and only store a reference (filename, author, title, etc.) to objectdb.
